club/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', ClubDashboard.as_view(),
         name='miembros'),
    path('miembros', MiembrosListView.as_view(),
         name='miembros-list'),
    path('<int:pk>', MiembroDetailView.as_view(),
         name='miembro-detail'),
    path('<int:pk>/', MiembroUpdateView.as_view(),
         name='miembro-update'),
    path('new/', MiembroCreateView.as_view(),
         name='miembro-new'),

    path('calendar-cumple', CalendarioCumples.as_view(), name='calendar-cumple'),

    path('familia/New/', FamiliaCreateView.as_view(),
         name='familia-new'),
    path('familia/<int:pk>', FamiliaDetailView.as_view(),
         name='familia-detail'),
]

contabilidad/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    # # Dashboard
    path('mensual', ContabilidadTemplateView.as_view(),
         name='contabilidad-mensual'),
    path('', ContabilidadAnualTemplateView.as_view(),
         name='contabilidad'),
    # entrada
    path('conceptopago', ConceptoEntradaListView.as_view(),
         name='conceptopago'),

    # entrada
    path('entradas', EntradasListView.as_view(),
         name='entradas'),
    path('entrada/<int:pk>', EntradaDetailView.as_view(),
         name='entrada-detail'),
    path('entrada/new/', EntradaCreateViews.as_view(),
         name='entrada-new'),

    # salidas
    path('salida', SalidasListView.as_view(),
         name='salidas'),
    path('salida/<int:pk>', SalidaDetailView.as_view(),
         name='salida-detail'),
    path('salida/new/', SalidaCreateViews.as_view(),
         name='salida-new'),
]

django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('gobernar/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('dashboard.urls')),
    path('club/', include('club.urls')),
    path('contabilidad/', include('contabilidad.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

club/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from dateutil.relativedelta import relativedelta
from django.utils.html import format_html


class TipoMiembro(models.Model):
    descripcion = models.CharField(max_length=100)

    class Meta:
        ordering = ['descripcion']
        verbose_name = 'Tipo de miembro'
        verbose_name_plural = 'Tipos de miembros'

    def __str__(self):
        return self.descripcion


class ClaseMiembro(models.Model):
    descripcion = models.CharField(max_length=100)
    hexcolor = models.CharField(max_length=7, default="#000000")

    @property
    def colored_name(self):
        return format_html(
            '<span style="color: #{};">{}</span>',
            self.hexcolor,
        )

    class Meta:
        ordering = ['descripcion']
        verbose_name = 'Clase de miembro'
        verbose_name_plural = 'Clases de miembros'

    def __str__(self):
        return self.descripcion


class Familia(models.Model):
    nombre_familia = models.CharField(max_length=200)

    class Meta:
        ordering = ['nombre_familia']
        verbose_name = 'Familia'
        verbose_name_plural = 'Familias'

    def __str__(self):
        return f'Familia {self.nombre_familia}'

    # ABSOLUTE URL METHOD
    def get_absolute_url(self):
        return reverse('familia-detail', kwargs={'pk': self.id})


class Miembro(models.Model):
    # CHOICES Sexo
    SEXO_M = 'M'
    SEXO_F = 'F'
    SEXO_CHOICES = (
        (SEXO_M, 'Masculino'),
        (SEXO_F, 'Femenino'),
    )

    # Datos de la persona
    nombre = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    apellido_materno = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    sexo = models.CharField(choices=SEXO_CHOICES, max_length=1)
    familia = models.ForeignKey(
        Familia,
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

    # Datos del club
    tipo_miembro = models.ForeignKey(
        TipoMiembro,
        on_delete=models.PROTECT)
    clase = models.ForeignKey(
        ClaseMiembro,
        on_delete=models.PROTECT)
    miembro_iglesia = models.BooleanField(default=True,
                                          verbose_name='¿Es miembro de la IASD?')

    class Meta:
        ordering = ['nombre', 'clase']
        verbose_name = 'miembro'
        verbose_name_plural = 'miembros'

    def __str__(self):
        return f'{self.nombre} {self.apellido_paterno} {self.apellido_materno} - {self.tipo_miembro}'

    # ABSOLUTE URL METHOD
    def get_absolute_url(self):
        return reverse('miembro-detail', kwargs={'pk': self.id})

    def get_absolute_url_update(self):
        """Returns the url to access a detail record for this cliente."""
        return reverse('miembro-update', args=[int(self.id)])

    @property
    def edad(self):
        return relativedelta(datetime.now().date(), self.fecha_nacimiento).years

    @property
    def edad_por_anio(self):
        return datetime.now().date().year - self.fecha_nacimiento.year

contabilidad/models.py
from django.urls import reverse
from django.db import models
from club.models import Miembro
from django.db.models import Sum
import uuid


class CuentaContable(models.Model):
    cuenta = models.CharField(max_length=25)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return f'{self.cuenta }'


class Concepto(models.Model):
    concepto = models.CharField(max_length=25)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return f'{self.concepto}'


class Entrada(models.Model):
    folio = models.CharField(max_length=8, blank=True)
    fecha_pago = models.DateField()
    de = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT,
    )
    notas = models.TextField(blank=True)

    # class Meta:
    #     ordering = ['fecha_pago', 'id']

    def __str__(self):
        return f'{self.id} - {self.de} por: ${self.total_importe}'

    def get_absolute_url(self):
        return reverse('entrada-detail', kwargs={'pk': self.pk})

    @property
    def mes_pago(self):
        return self.fecha_pago.month

    @property
    def anio_pago(self):
        return self.fecha_pago.year

    @property
    def total_importe(self):
        return ConceptoEntrada.objects.filter(entrada=self).aggregate(Sum('importe'))['importe__sum']

    @property
    def conceptos(self):
        return ', '.join(ConceptoEntrada.objects.filter(entrada=self).values_list('concepto__concepto', flat=True))

    @property
    def cuentacontables(self):
        return ', '.join(ConceptoEntrada.objects.filter(entrada=self).values_list('cuenta_contable__cuenta', flat=True))


class ConceptoEntrada(models.Model):
    entrada = models.ForeignKey(
        Entrada,
        on_delete=models.CASCADE,
    )
    miembro = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT
    )
    concepto = models.ForeignKey(
        Concepto,
        on_delete=models.PROTECT,
    )
    cuenta_contable = models.ForeignKey(
        CuentaContable,
        on_delete=models.CASCADE,
    )
    importe = models.FloatField()

    def __str__(self):
        return f'pago para {self.miembro} por {self.concepto} por {self.importe}'


class Salida(models.Model):
    folio = models.CharField(max_length=30, blank=True)
    fecha_pago = models.DateField()
    de = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT,
    )
    proveedor = models.CharField(
        max_length=100
    )
    notas = models.TextField(blank=True)

    # class Meta:
    #     ordering = ['fecha_pago', 'proveedor']

    def get_absolute_url(self):
        return reverse('salida-detail', kwargs={'pk': self.pk})

    @property
    def mes_pago(self):
        return self.fecha_pago.month

    @property
    def anio_pago(self):
        return self.fecha_pago.year

    @property
    def total_importe(self):
        return ConceptoSalida.objects.filter(salida=self).aggregate(Sum('importe'))['importe__sum']

    @property
    def conceptos(self):
        return ', '.join(ConceptoSalida.objects.filter(salida=self).values_list('concepto', flat=True))

    @property
    def cuentacontables(self):
        return ', '.join(ConceptoSalida.objects.filter(salida=self).values_list('cuenta_contable__cuenta', flat=True))


class ConceptoSalida(models.Model):
    salida = models.ForeignKey(
        Salida,
        on_delete=models.PROTECT,
    )
    concepto = models.CharField(max_length=100)
    cuenta_contable = models.ForeignKey(
        CuentaContable,
        on_delete=models.CASCADE,
    )
    importe = models.FloatField()

    def __str__(self):
        return f'{self.concepto} ${self.importe}'

contabilidad/forms.py
from django import forms
from django.shortcuts import render
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Div, Fieldset, HTML, ButtonHolder, Submit
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab
from django.forms import inlineformset_factory
from django.template.loader import render_to_string
from crispy_forms.layout import LayoutObject, TEMPLATE_PACK

from . import models


class Formset(LayoutObject):
    template = "contabilidad/formset.html"

    def __init__(self, formset_name_in_context, template=None):
        self.formset_name_in_context = formset_name_in_context
        self.fields = []
        if template:
            self.template = template

    def render(self, form, context, template_pack=TEMPLATE_PACK, **kwargs):
        template = self.get_template_name(template_pack)
        formset = context[self.formset_name_in_context]
        return render_to_string(template, {'formset': formset})


class ConceptoEntradaForm(forms.ModelForm):
    class Meta:
        model = models.ConceptoEntrada
        exclude = ()


class ConceptoSalidaForm(forms.ModelForm):
    class Meta:
        model = models.ConceptoSalida
        exclude = ()


class EntradaForm(forms.ModelForm):

    class Meta:
        model = models.Entrada
        fields = ['fecha_pago', 'de', 'notas']
        widgets = {
            'fecha_pago': forms.DateInput(attrs={'id': 'datepicker'}),
            # 'de': forms.DateInput(attrs={'class': 'select form-select'}),
        }

    def __init__(self, *args, **kwargs):
        super(EntradaForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        # self.helper.form_class = 'form-horizontal'
        # self.helper.label_class = 'col-md-3 create-label'
        # self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Fieldset('Datos generales',
                         Row(
                             Column(Field('fecha_pago'),
                                    css_class='form-group col-md-4 mb-0'),
                             Column(Field('de', css_class="select-js"),
                                    css_class='form-group col mb-0'),
                         ),
                         ),
                # Field('fecha_pago'),
                # Field('de'),
                Fieldset('Conceptos del Entrada',
                         Formset('concepto')
                         ),
                Field('notas'),
                # Fieldset('Agregar documento',
                #          Formset('documento')),

                HTML("<br>"),
                ButtonHolder(Submit('submit', 'Guardar')),
            )
        )


class SalidaForm(forms.ModelForm):

    class Meta:
        model = models.Salida
        fields = ['folio', 'proveedor', 'de', 'fecha_pago', 'notas']
        widgets = {
            'fecha_pago': forms.DateInput(attrs={'id': 'datepicker'}),
        }

    def __init__(self, *args, **kwargs):
        super(SalidaForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_tag = True
        # self.helper.form_class = 'form-horizontal'
        # self.helper.label_class = 'col-md-3 create-label'
        # self.helper.field_class = 'col-md-9'
        self.helper.layout = Layout(
            Div(
                Fieldset('Datos generales',
                         Row(
                             Column(Field('fecha_pago'),
                                    css_class='form-group col-md-4 mb-0'),
                             Column(Field('de', css_class="select-js"),
                                    css_class='form-group col-md-4 mb-0'),
                             Column(Field('folio'),
                                    css_class='form-group col-md-4 mb-0'),
                         ),
                         Row(
                             Field('proveedor'),
                         ),
                         ),
                # Field('folio'),
                # Field('proveedor'),
                # Field('fecha_pago'),
                Fieldset('Conceptos del Salida',
                         Formset('concepto')
                         ),
                Field('notas'),
                # Fieldset('Agregar documento',
                #          Formset('documento')),

                HTML("<br>"),
                ButtonHolder(Submit('submit', 'Guardar')),
            )
        )


ConceptoEntradaFormSet = inlineformset_factory(
    models.Entrada, models.ConceptoEntrada, form=ConceptoEntradaForm,
    fields=['miembro',  'concepto', 'cuenta_contable', 'importe'], extra=2, can_delete=True
)

ConceptoSalidaFormSet = inlineformset_factory(
    models.Salida, models.ConceptoSalida, form=ConceptoSalidaForm,
    fields=['concepto', 'cuenta_contable', 'importe'], extra=1, can_delete=True
)

contabilidad/templates/contabilidad/contabilidad.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Contabilidad del mes {{calendario.mes_nombre}}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="dropdown  me-2">
            <button class="btn btn-sm btn-outline-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Mes
            </button>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=1 ">Enero</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=2 ">Febrero</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=3 ">Marzo</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=4 ">Abril</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=5 ">Mayo</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=6 ">Junio</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=7 ">Julio</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=8 ">Agosto</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=9 ">Setptiembre</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=10 ">Octubre</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=11 ">Noviembre</a></li>
                <li><a class="dropdown-item" href="{% url 'contabilidad-mensual'%}?mes=12 ">Diciembre</a></li>
            </ul>
        </div>

        <div class="btn-group  me-2" role="group" aria-label="Basic example">

            {% if perms.contabilidad.view_entrada %}
            <a href="{% url 'entradas' %}" class="btn btn-sm btn-outline-secondary">
                <i data-feather="trending-up"></i> Ingresos
            </a>
            {% endif %}
            {% if perms.contabilidad.add_entrada %}
            <a href="{% url 'entrada-new' %}" class="btn btn-sm btn-outline-secondary ">
                <i class="text-success" data-feather="plus-circle"></i> Nuevo Ingreso
            </a>
            {% endif %}
            {% if perms.contabilidad.view_salida %}
            <a href="{% url 'salidas' %}" class="btn btn-sm btn-outline-secondary ">
                <i data-feather="trending-down"></i> Egresos
            </a>
            {% endif %}
            {% if perms.contabilidad.add_salida %}
            <a href="{% url 'salida-new' %}" class="btn btn-sm btn-outline-secondary">
                <i class="text-danger" data-feather="minus-circle"></i> Nuevo Egreso
            </a>
            {% endif %}
        </div>
    </div>
</div>


<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'contabilidad'%}">Contabilidad</a></li>
        <li class="breadcrumb-item active" aria-current="page">Contabilidad de {{calendario.mes_nombre}}</li>
    </ol>
</nav>


<div class="row my-4">
    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
        <div class="card shadow h-100">
            <h5 class="card-header bg-info text-white">Saldo anterior</h5>
            <div class="card-body">
                <h5 class="card-title">${{pagos_anteriores_importe|floatformat:2|intcomma}}</h5>
                <p class="card-text">Saldo anterior de los meses anteriores</p>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
        <div class="card shadow h-100">
            <h5 class="card-header bg-info text-white">Total de Ingresos</h5>
            <div class="card-body">
                <h5 class="card-title">${{pagos_mes_actual_importe.importe__sum|floatformat:2|intcomma}}</h5>
                <p class="card-text">Mes de {{calendario.mes_nombre}}, con un total de {{pagos_mes_actual_conteo}}
                    ingresos
                </p>
                <!-- <p class="card-text text-success">18.2% increase since last month</p> -->
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
        <div class="card shadow h-100 ">
            <h5 class="card-header bg-info text-white">Total de Egresos</h5>
            <div class="card-body">
                <h5 class="card-title">${{salidas_mes_actual_importe.importe__sum|floatformat:2|intcomma}}</h5>
                <p class="card-text">Mes de {{calendario.mes_nombre}}, con un total de {{salidas_mes_actual_conteo}}
                    egresos
                </p>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
        <div class="card shadow h-100">
            <h5 class="card-header bg-info text-white">Saldo final</h5>
            <div class="card-body">
                {% if saldo > 0 %}
                <h5 class="card-title text-success ">${{saldo|floatformat:2|intcomma}}</h5>
                <p class="card-text">Saldo a favor</p>
                {% elif saldo == 0 %}
                <h5 class="card-title">${{saldo|floatformat:2|intcomma}}</h5>
                <p class="card-text">Ni una ni otra</p>
                {% elif saldo < 0 %} <h5 class="card-title text-danger">${{saldo|floatformat:2|intcomma}}</h5>
                    <p class="card-text">Saldo en contra</p>
                    {% else %}
                    <h5 class="card-title">${{saldo|floatformat:2|intcomma}}</h5>
                    <p class="card-text">Sin cambios aun</p>
                    {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="card shadow-sm ">
            <h5 class="card-header bg-secondary text-white">Ingresos del mes <i data-feather="trending-up"></i></h5>
            <div class="card-body">
                {% if entradas_list %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm small" id="dataTable">
                        <caption>Lista de ingresos</caption>
                        <thead>
                            <tr>
                                <th scope="col" class="text-center">Recibo</th>
                                <th scope="col">Fecha de pago</th>
                                <th scope="col">Miembro</th>
                                <th scope="col">Concepto</th>
                                <th scope="col">Uso</th>
                                <th scope="col" class="text-end">Importe</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for entrada in entradas_list %}
                            <tr>
                                <th scope="row" class="font-monospace text-center">
                                    {% if entrada.folio %}
                                    {{entrada.folio}}
                                    {% else %}
                                    {{entrada.id}}
                                    {% endif %}
                                </th>
                                <td>{{entrada.fecha_pago}}</td>
                                <td><a href="{{entrada.de.get_absolute_url}}" class="">{{entrada.de}}</a>
                                </td>
                                <td>{{entrada.conceptos}}</td>
                                <td>{{entrada.cuentacontables}}</td>
                                <td class="text-end">${{entrada.total_importe|floatformat:2|intcomma}}</td>
                                <td class="text-center">
                                    <a href="{{entrada.get_absolute_url}}" class="">Ver</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td class="text-end">
                                    ${{pagos_mes_actual_importe.importe__sum|floatformat:2|intcomma}}
                                </td>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                {% endif %}
                <a href="{% url 'entradas' %}" class="btn btn-block btn-light">Ver todos los ingresos</a>
            </div>
        </div>
    </div>
</div>
<div class="row my-4">
    <div class="col">
        <div class="card shadow-sm ">
            <h5 class="card-header bg-secondary text-white">
                Egresos del mes <i data-feather="trending-down"></i>
            </h5>
            <div class="card-body">
                {% if salidas_list %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm small" id="dataTable">
                        <caption>Lista de egresos</caption>
                        <thead>
                            <tr>
                                <th scope="col" class="text-center">Recibo</th>
                                <th scope="col">Fecha de pago</th>
                                <th scope="col">Proveedor</th>
                                <th scope="col">Conceptos</th>
                                <th scope="col" class="text-end">Importe</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for salida in salidas_list %}
                            <tr>
                                <th scope="row" class="font-monospace text-center">
                                    {{salida.folio}}
                                </th>
                                <td>{{salida.fecha_pago}}</td>
                                <td>{{salida.proveedor}}</td>
                                <td>{{salida.conceptos}}</td>
                                <td class="text-end">${{salida.total_importe|floatformat:2|intcomma}}</td>
                                <td class="text-center">
                                    <a href="{{salida.get_absolute_url}}" class="">Ver</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td class="text-end">
                                    ${{salidas_mes_actual_importe.importe__sum|floatformat:2|intcomma}}
                                </td>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                {% endif %}
                <a href="{% url 'salidas' %}" class="btn btn-block btn-light">Ver todos los egresos</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}



{% block JavaScript %}


{% endblock %}

contabilidad/templates/contabilidad/entrada_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'contabilidad' %}">Contabilidad</a></li>
        <li class="breadcrumb-item"><a href="{% url 'entradas' %}">Ingreso</a></li>
        <li class="breadcrumb-item active" aria-current="page">Entrada #{{entrada.id}}</li>
    </ol>
</nav>
<div class="d-flex align-items-center justify-content-md-end mt-3 mt-md-0">
    {% if perms.contabilidad.add_entrada %}
    <a href="{% url 'entrada-new' %}" class="btn btn-sm btn-outline-secondary ">
        <i class="text-success" data-feather="plus-circle"></i> Nuevo Ingreso
    </a>
    {% endif %}
</div>
<div class="container mt-5 mb-3">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card shadow">
                <div class="d-flex flex-row p-4 "> <img src="https://mundoja.org/images/a1-nuevo-web.png" width="72"
                        height="72s">
                    <div class="d-flex flex-column"> <span class="font-weight-bold">Entrada de ingreso</span>
                        <small class="">
                            Folio:
                            <small class="font-monospace text-danger">
                                {{entrada.folio}}
                            </small>
                        </small>
                        <small class="">
                            Fecha de pago:
                            <small class="">
                                {{entrada.fecha_pago}}
                            </small>
                        </small>
                    </div>
                </div>
                <hr>
                <div class="table-responsive p-4">
                    <table class="table table-borderless">
                        <tbody>
                            <tr class="add">
                                <td>De:</td>
                                <td>Para:</td>
                            </tr>
                            <tr class="content">
                                <td class="font-weight-bold">
                                    {{entrada.de}}
                                    <br>{{entrada.miembro.get_clase_display}}
                                </td>
                                <td class="font-weight-bold">Club de aventureros Peniel</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <hr>
                <div class="products p-4">
                    <table class="table table-borderless">
                        <tbody>
                            <tr class="add">
                                <td class="font-weight-bold">Para:</td>
                                <td class="font-weight-bold">Concepto:</td>
                                <td class="font-weight-bold text-center">Total:</td>
                            </tr>
                            {% for concepto in entrada.conceptoentrada_set.all %}
                            <tr class="content">
                                <td>{{concepto.miembro}}</td>
                                <td>{{concepto.concepto}}</td>
                                <td class="text-center">${{concepto.importe|floatformat:2|intcomma}}</td>
                            </tr>
                            {% endfor %}
                            <tr class="content">
                                <td class=""></td>
                                <td class=""></td>
                                <td class="text-center font-weight-bold border-top">
                                    ${{entrada.total_importe|floatformat:2|intcomma}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <hr>
                {% if entrada.notas %}
                <div class="products p-4">
                    <table class="table table-borderless">
                        <tbody>
                            <tr class="add">
                                <td class="font-weight-bold">Notas:</td>
                            </tr>
                            <tr class="content">
                                <td class="text-left">{{entrada.notas}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <hr>
                {% endif %}
                <div class="address p-4">
                    <table class="table table-borderless">
                        <tbody>
                            <tr class="add">
                                <td>Iglesia Adventista del Séptimo Día - Narvarte</td>
                            </tr>
                            <tr class="content">
                                <td>
                                    Uxmal 363, Narvarte Poniente, <br>Benito Juárez, <br>03020 Ciudad de México,
                                    <br>CDMX
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block JavaScript %}

{% endblock %}