club/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', ClubDashboard.as_view(),
         name='miembros'),
    path('miembros', MiembrosListView.as_view(),
         name='miembros-list'),
    path('<int:pk>', MiembroDetailView.as_view(),
         name='miembro-detail'),
    path('<int:pk>/', MiembroUpdateView.as_view(),
         name='miembro-update'),
    path('new/', MiembroCreateView.as_view(),
         name='miembro-new'),

    path('calendar-cumple', CalendarioCumples.as_view(), name='calendar-cumple'),

    path('familia/New/', FamiliaCreateView.as_view(),
         name='familia-new'),
    path('familia/<int:pk>', FamiliaDetailView.as_view(),
         name='familia-detail'),
]

dashboard/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', DashboardTemplateView.as_view(),
         name='home'),
    path('reportes', ReportesTemplateView.as_view(),
         name='reportes'),
         
    path('reportes/reporte-pagos-conceptos', PagosConceptoTemplateView.as_view(),
         name='reporte-pagos-conceptos'),
    path('reportes/reporte-pagos-cuotas', CuotasTemplateView.as_view(),
         name='reporte-pagos-cuotas'),
    path('reportes/reporte-pagos-camporee', CamporeeTemplateView.as_view(),
         name='reporte-pagos-camporee'),
    path('reportes/reporte_mensual_pagos', reporte_mensual_pagos,
         name='reporte_mensual_pagos'),
    path('reportes/reporte-recoleccion', RecoleccionTemplateView.as_view(),
         name='reporte-recoleccion'),
]

django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('gobernar/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('dashboard.urls')),
    path('club/', include('club.urls')),
    path('contabilidad/', include('contabilidad.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

club/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from dateutil.relativedelta import relativedelta
from django.utils.html import format_html


class TipoMiembro(models.Model):
    descripcion = models.CharField(max_length=100)

    class Meta:
        ordering = ['descripcion']
        verbose_name = 'Tipo de miembro'
        verbose_name_plural = 'Tipos de miembros'

    def __str__(self):
        return self.descripcion


class ClaseMiembro(models.Model):
    descripcion = models.CharField(max_length=100)
    hexcolor = models.CharField(max_length=7, default="#000000")

    @property
    def colored_name(self):
        return format_html(
            '<span style="color: #{};">{}</span>',
            self.hexcolor,
        )

    class Meta:
        ordering = ['descripcion']
        verbose_name = 'Clase de miembro'
        verbose_name_plural = 'Clases de miembros'

    def __str__(self):
        return self.descripcion


class Familia(models.Model):
    nombre_familia = models.CharField(max_length=200)

    class Meta:
        ordering = ['nombre_familia']
        verbose_name = 'Familia'
        verbose_name_plural = 'Familias'

    def __str__(self):
        return f'Familia {self.nombre_familia}'

    # ABSOLUTE URL METHOD
    def get_absolute_url(self):
        return reverse('familia-detail', kwargs={'pk': self.id})


class Miembro(models.Model):
    # CHOICES Sexo
    SEXO_M = 'M'
    SEXO_F = 'F'
    SEXO_CHOICES = (
        (SEXO_M, 'Masculino'),
        (SEXO_F, 'Femenino'),
    )

    # Datos de la persona
    nombre = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    apellido_materno = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    sexo = models.CharField(choices=SEXO_CHOICES, max_length=1)
    familia = models.ForeignKey(
        Familia,
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

    # Datos del club
    tipo_miembro = models.ForeignKey(
        TipoMiembro,
        on_delete=models.PROTECT)
    clase = models.ForeignKey(
        ClaseMiembro,
        on_delete=models.PROTECT)
    miembro_iglesia = models.BooleanField(default=True,
                                          verbose_name='¿Es miembro de la IASD?')

    class Meta:
        ordering = ['nombre', 'clase']
        verbose_name = 'miembro'
        verbose_name_plural = 'miembros'

    def __str__(self):
        return f'{self.nombre} {self.apellido_paterno} {self.apellido_materno} - {self.tipo_miembro}'

    # ABSOLUTE URL METHOD
    def get_absolute_url(self):
        return reverse('miembro-detail', kwargs={'pk': self.id})

    def get_absolute_url_update(self):
        """Returns the url to access a detail record for this cliente."""
        return reverse('miembro-update', args=[int(self.id)])

    @property
    def edad(self):
        return relativedelta(datetime.now().date(), self.fecha_nacimiento).years

    @property
    def edad_por_anio(self):
        return datetime.now().date().year - self.fecha_nacimiento.year

contabilidad/models.py
from django.urls import reverse
from django.db import models
from club.models import Miembro
from django.db.models import Sum
import uuid


class CuentaContable(models.Model):
    cuenta = models.CharField(max_length=25)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return f'{self.cuenta }'


class Concepto(models.Model):
    concepto = models.CharField(max_length=25)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return f'{self.concepto}'


class Entrada(models.Model):
    folio = models.CharField(max_length=8, blank=True)
    fecha_pago = models.DateField()
    de = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT,
    )
    notas = models.TextField(blank=True)

    # class Meta:
    #     ordering = ['fecha_pago', 'id']

    def __str__(self):
        return f'{self.id} - {self.de} por: ${self.total_importe}'

    def get_absolute_url(self):
        return reverse('entrada-detail', kwargs={'pk': self.pk})

    @property
    def mes_pago(self):
        return self.fecha_pago.month

    @property
    def anio_pago(self):
        return self.fecha_pago.year

    @property
    def total_importe(self):
        return ConceptoEntrada.objects.filter(entrada=self).aggregate(Sum('importe'))['importe__sum']

    @property
    def conceptos(self):
        return ', '.join(ConceptoEntrada.objects.filter(entrada=self).values_list('concepto__concepto', flat=True))

    @property
    def cuentacontables(self):
        return ', '.join(ConceptoEntrada.objects.filter(entrada=self).values_list('cuenta_contable__cuenta', flat=True))


class ConceptoEntrada(models.Model):
    entrada = models.ForeignKey(
        Entrada,
        on_delete=models.CASCADE,
    )
    miembro = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT
    )
    concepto = models.ForeignKey(
        Concepto,
        on_delete=models.PROTECT,
    )
    cuenta_contable = models.ForeignKey(
        CuentaContable,
        on_delete=models.CASCADE,
    )
    importe = models.FloatField()

    def __str__(self):
        return f'pago para {self.miembro} por {self.concepto} por {self.importe}'


class Salida(models.Model):
    folio = models.CharField(max_length=30, blank=True)
    fecha_pago = models.DateField()
    de = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT,
    )
    proveedor = models.CharField(
        max_length=100
    )
    notas = models.TextField(blank=True)

    # class Meta:
    #     ordering = ['fecha_pago', 'proveedor']

    def get_absolute_url(self):
        return reverse('salida-detail', kwargs={'pk': self.pk})

    @property
    def mes_pago(self):
        return self.fecha_pago.month

    @property
    def anio_pago(self):
        return self.fecha_pago.year

    @property
    def total_importe(self):
        return ConceptoSalida.objects.filter(salida=self).aggregate(Sum('importe'))['importe__sum']

    @property
    def conceptos(self):
        return ', '.join(ConceptoSalida.objects.filter(salida=self).values_list('concepto', flat=True))

    @property
    def cuentacontables(self):
        return ', '.join(ConceptoSalida.objects.filter(salida=self).values_list('cuenta_contable__cuenta', flat=True))


class ConceptoSalida(models.Model):
    salida = models.ForeignKey(
        Salida,
        on_delete=models.PROTECT,
    )
    concepto = models.CharField(max_length=100)
    cuenta_contable = models.ForeignKey(
        CuentaContable,
        on_delete=models.CASCADE,
    )
    importe = models.FloatField()

    def __str__(self):
        return f'{self.concepto} ${self.importe}'

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms
from django.shortcuts import render
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Div, Fieldset, HTML
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab


class ReporteMensualPagoForm(forms.Form):
    # CHOICES
    ENERO = 1
    FEBRERO = 2
    MARZO = 3
    ABRIL = 4
    MAYO = 5
    JUNIO = 6
    JULIO = 7
    AGOSTO = 8
    SEPTIEMBRE = 9
    OCTUBRE = 10
    NOVIEMBRE = 11
    DICIEMBRE = 12

    MESES_CHOICES = (
        (ENERO, '01 - ENERO'),
        (FEBRERO, '02 - FEBRERO'),
        (MARZO, '03 - MARZO'),
        (ABRIL, '04 - ABRIL'),
        (MAYO, '05 - MAYO'),
        (JUNIO, '06 - JUNIO'),
        (JULIO, '07 - JULIO'),
        (AGOSTO, '08 - AGOSTO'),
        (SEPTIEMBRE, '09 - SEPTIEMBRE'),
        (OCTUBRE, '10 - OCTUBRE'),
        (NOVIEMBRE, '11 - NOVIEMBRE'),
        (DICIEMBRE, '12 - DICIEMBRE'),
    )
    anio = forms.IntegerField(
        min_value=2019,
        label='Año'
    )
    mes = forms.ChoiceField(
        choices=MESES_CHOICES,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            HTML('''
            <h3>Selecciona un mes en particular para revisar</h3>
            <p>
            Selecciona un año y un mes en particular para revisar
            los pagos que se han realizado durante el mes seleccionado
            </p>
            '''),
            Field('anio'),
            Field('mes'),
        )
        self.helper.add_input(Submit('submit', 'Aceptar'))


# class PermisoEspecialForm(forms.Form):
#     roles = forms.MultipleChoiceField()
#     nominas = forms.MultipleChoiceField()
#     # user = forms.ModelChoiceField(
#     #     queryset=CustomUser.objects.all(),
#     #     widget=forms.HiddenInput()
#     # )

#     roles.widget.attrs.update(size='10')
#     nominas.widget.attrs.update(size='10')

#     def __init__(self, ambiente, *args, **kwargs):
#         super(PermisoEspecialForm, self).__init__(*args, **kwargs)
#         rol = lista_rol_ambiente_choices(ambiente)
#         elementos = lista_elementopermiso_ambiente_choices(ambiente)
#         self.fields['roles'].choices = rol
#         self.fields['nominas'].choices = elementos
#         # self.fields['tipo_apertura'].label = "Tipo de apertura"
#         self.helper = FormHelper()
#         self.helper.add_input(
#             Submit('submit', 'Aceptar', css_class='btn-success'))

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block header %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">

{% endblock %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
</div>
<p>Este tablero muestra los datos más relevantes e importantes del club</p>

<div
    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom  my-4">
    <h1 class="h3">Contabilidad</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group  me-2" role="group" aria-label="Basic example">
            {% if perms.contabilidad.view_entrada or perms.contabilidad.view_salida%}
            <a href="{% url 'contabilidad' %}" class="btn btn-sm btn-outline-secondary ">
                <i data-feather="dollar-sign"></i> Ver contabilidad
            </a>
            {% endif %}
            {% if perms.contabilidad.add_entrada %}
            <a href="{% url 'entrada-new' %}" class="btn btn-sm btn-outline-secondary ">
                <i class="text-success" data-feather="plus-circle"></i> Nuevo Ingreso
            </a>
            {% endif %}
            {% if perms.contabilidad.add_salida %}
            <a href="{% url 'salida-new' %}" class="btn btn-sm btn-outline-secondary">
                <i class="text-danger" data-feather="minus-circle"></i> Nuevo Egreso
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% if perms.contabilidad.view_entrada or perms.contabilidad.view_salida%}

<div class="row">
    {% if perms.contabilidad.view_entrada %}
    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
        <div class="card shadow h-100">
            <h5 class="card-header bg-info text-white">Total de Ingresos</h5>
            <div class="card-body">
                <h5 class="card-title">${{entrada_mes_actual_importe.importe__sum|floatformat:2|intcomma}}</h5>
                <p class="card-text">Con un total de {{entradas_mes_actual_conteo}} ingresos
                </p>
                <!-- <p class="card-text text-success">18.2% increase since last month</p> -->
            </div>
        </div>
    </div>
    {% endif %}
    {% if perms.contabilidad.view_salida %}
    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
        <div class="card shadow h-100">
            <h5 class="card-header bg-info text-white">Total de Egresos</h5>
            <div class="card-body">
                <h5 class="card-title">${{salidas_mes_actual_importe.importe__sum|floatformat:2|intcomma}}</h5>
                <p class="card-text">Con un total de {{salidas_mes_actual_conteo}} egresos
                </p>
            </div>
        </div>
    </div>
    {% endif %}
    {% if perms.contabilidad.view_entrada and perms.contabilidad.view_salida%}
    <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
        <div class="card shadow h-100">
            <h5 class="card-header bg-info text-white">Saldo del mes</h5>
            <div class="card-body">
                {% if saldo > 0 %}
                <h5 class="card-title text-success ">${{saldo|floatformat:2|intcomma}}</h5>
                <p class="card-text">Saldo a favor</p>
                {% elif saldo == 0 %}
                <h5 class="card-title">${{saldo|floatformat:2|intcomma}}</h5>
                <p class="card-text">Ni una ni otra</p>
                {% elif saldo < 0 %} <h5 class="card-title text-danger">${{saldo|floatformat:2|intcomma}}</h5>
                    <p class="card-text">Saldo en contra</p>
                    {% else %}
                    <h5 class="card-title">${{saldo|floatformat:2|intcomma}}</h5>
                    <p class="card-text">Sin cambios aun</p>
                    {% endif %}
            </div>
        </div>
        {% endif %}
    </div>
    <!-- <div class="col-12 col-md-6 mb-4 mb-lg-0 col-lg-3">
    <div class="card shadow-sm h-100">
      <h5 class="card-header bg-info text-white">Pendientes reembolso</h5>
      <div class="card-body">
        <h5 class="card-title">64k</h5>
        <p class="card-text">Feb 1 - Apr 1, United States</p>
      </div>
    </div>
  </div> -->
</div>
{% else %}
<div class="row">
    <div class="col">
        <p>Sin permisos</p>
    </div>
</div>

{% endif %}

<div
    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom  my-4">
    <h1 class="h3">Miembros y familias</h1>
    <div class="btn-toolbar mb-2 mb-md-0">

        <div class="btn-group me-2" role="group" aria-label="Basic example">
            <a class="btn btn-sm btn-outline-primary" href="{% url 'miembros' %}"> Ver miembros</a>
            <a class="btn btn-sm btn-outline-primary" href="{% url 'calendar-cumple' %}"> Cumpleaños</a>
            {% if perms.club.add_familia %}
            <a href="{% url 'familia-new' %}" class="btn btn-sm btn-outline-secondary">
                <i class="text-success" data-feather="user-plus"></i> Nueva familia
            </a>
            {% endif %}
            {% if perms.club.add_miembro %}
            <a href="{% url 'miembro-new' %}" class="btn btn-sm btn-outline-secondary">
                <i class="text-success" data-feather="user-plus"></i> Nuevo miembro
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% if perms.club.view_miembro %}
<div class="row my-4">
    <div class="col mb-4 mb-lg-0">
        <div class="row row-cols-1 row-cols-md-4 g-4">
            {% for key,value in tipo_miembro_count.items %}
            <div class="col">
                <div class="card shadow h-100">
                    <h5 class="card-header bg-primary text-white">{{value.tipo_miembro}}</h5>
                    <div class="card-body">
                        <h5 class="card-title">{{value.counts}}</h5>
                        <p class="card-text">Total de {{value.tipo_miembro}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="col">
                <div class="card shadow h-100">
                    <h5 class="card-header bg-primary text-white">Total de miembros</h5>
                    <div class="card-body">
                        <h5 class="card-title">{{miembro_count}}</h5>
                        <p class="card-text">Total de todos</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- <div class="row my-4">
    <div class="col mb-4 mb-lg-0">
        <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
                <div class="card shadow h-100">
                    <h5 class="card-header bg-primary text-white">Aventureros</h5>
                    <div class="card-body">
                        <canvas id="AventurerosCount"></canvas>
                        {{miembros_tipos|safe}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> -->
{% else %}
<div class="row my-4">
    <div class="col">
        <p>Sin permisos</p>
    </div>
</div>
{% endif %}


{% endblock %}


{% block JavaScript %}

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

{{ claseAventureros|json_script:"claseAventureros" }}

<script>
    const value = JSON.parse(document.getElementById('claseAventureros').textContent);
    const ctx = document.getElementById('AventurerosCount');

    new Chart(ctx, {
        type: 'doughnut',
        data: {
            labels: value.labels,
            datasets: [{
                label: 'Total',
                data: value.data,
                backgroundColor: value.colors,
            }]
        },
        options: {
            responsive: true,
            plugins: {
                legend: {
                    position: 'bottom',
                    display: true,
                },
                title: {
                    display: false,
                    text: 'Aventureros por clase'
                }
            }
        }
    });
</script>
{% endblock %}

dashboard/templates/dashboard/reportes.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Reportes</li>
    </ol>
</nav>
<h1 class="h2">Reportes</h1>
<p>Seccion de reportes e informes</p>


<div
    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom  my-4">
    <h1 class="h4">Contabilidad</h1>
</div>
{% if perms.contabilidad.view_recibo or perms.contabilidad.view_gasto%}
<dl class="row">
    <dt class="col-sm-3">Reporte</dt>
    <dd class="col-sm-9">Descripcion del reporte</dd>
    <hr class="dropdown-divider">
    <dt class="col-sm-3">
        <a href="{% url 'reporte-pagos-conceptos' %}" class="">Reporte general de pagos por concepto</a>
    </dt>
    <dd class="col-sm-9">Muestra todos los pagos</dd>

    <dt class="col-sm-3">
        <a href="{% url 'reporte_mensual_pagos' %}" class="">Reporte de pagos por mes</a>
    </dt>
    <dd class="col-sm-9">Muestra los pagos realizados por mes y ordenados por fecha</dd>

    <dt class="col-sm-3">
        <a href="{% url 'reporte-pagos-cuotas' %}" class="">Reporte de cuotas</a>
    </dt>
    <dd class="col-sm-9">Muestra las cuotas pagadas</dd>

    <dt class="col-sm-3">
        <a href="{% url 'reporte-pagos-camporee' %}" class="">Reporte de camporee</a>
    </dt>
    <dd class="col-sm-9">Los pagos realizados para el camporee</dd>

    <dt class="col-sm-3">
        <a href="{% url 'reporte-recoleccion' %}" class="">Reporte de recolección</a>
    </dt>
    <dd class="col-sm-9">Muestra el avance de la recolección</dd>
</dl>
{% else %}
<p>Sin permisos</p>
{% endif %}

{% endblock %}