club/urls.py
from django.urls import path, include
from .views import *

urlpatterns = [
    path('', ClubDashboard.as_view(),
         name='miembros'),
    path('miembros', MiembrosListView.as_view(),
         name='miembros-list'),
    path('<int:pk>', MiembroDetailView.as_view(),
         name='miembro-detail'),
    path('<int:pk>/', MiembroUpdateView.as_view(),
         name='miembro-update'),
    path('new/', MiembroCreateView.as_view(),
         name='miembro-new'),

    path('calendar-cumple', CalendarioCumples.as_view(), name='calendar-cumple'),

    path('familia/New/', FamiliaCreateView.as_view(),
         name='familia-new'),
    path('familia/<int:pk>', FamiliaDetailView.as_view(),
         name='familia-detail'),
]

django_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('gobernar/', admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path('', include('dashboard.urls')),
    path('club/', include('club.urls')),
    path('contabilidad/', include('contabilidad.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

club/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from dateutil.relativedelta import relativedelta
from django.utils.html import format_html


class TipoMiembro(models.Model):
    descripcion = models.CharField(max_length=100)

    class Meta:
        ordering = ['descripcion']
        verbose_name = 'Tipo de miembro'
        verbose_name_plural = 'Tipos de miembros'

    def __str__(self):
        return self.descripcion


class ClaseMiembro(models.Model):
    descripcion = models.CharField(max_length=100)
    hexcolor = models.CharField(max_length=7, default="#000000")

    @property
    def colored_name(self):
        return format_html(
            '<span style="color: #{};">{}</span>',
            self.hexcolor,
        )

    class Meta:
        ordering = ['descripcion']
        verbose_name = 'Clase de miembro'
        verbose_name_plural = 'Clases de miembros'

    def __str__(self):
        return self.descripcion


class Familia(models.Model):
    nombre_familia = models.CharField(max_length=200)

    class Meta:
        ordering = ['nombre_familia']
        verbose_name = 'Familia'
        verbose_name_plural = 'Familias'

    def __str__(self):
        return f'Familia {self.nombre_familia}'

    # ABSOLUTE URL METHOD
    def get_absolute_url(self):
        return reverse('familia-detail', kwargs={'pk': self.id})


class Miembro(models.Model):
    # CHOICES Sexo
    SEXO_M = 'M'
    SEXO_F = 'F'
    SEXO_CHOICES = (
        (SEXO_M, 'Masculino'),
        (SEXO_F, 'Femenino'),
    )

    # Datos de la persona
    nombre = models.CharField(max_length=100)
    apellido_paterno = models.CharField(max_length=100)
    apellido_materno = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    sexo = models.CharField(choices=SEXO_CHOICES, max_length=1)
    familia = models.ForeignKey(
        Familia,
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

    # Datos del club
    tipo_miembro = models.ForeignKey(
        TipoMiembro,
        on_delete=models.PROTECT)
    clase = models.ForeignKey(
        ClaseMiembro,
        on_delete=models.PROTECT)
    miembro_iglesia = models.BooleanField(default=True,
                                          verbose_name='¿Es miembro de la IASD?')

    class Meta:
        ordering = ['nombre', 'clase']
        verbose_name = 'miembro'
        verbose_name_plural = 'miembros'

    def __str__(self):
        return f'{self.nombre} {self.apellido_paterno} {self.apellido_materno} - {self.tipo_miembro}'

    # ABSOLUTE URL METHOD
    def get_absolute_url(self):
        return reverse('miembro-detail', kwargs={'pk': self.id})

    def get_absolute_url_update(self):
        """Returns the url to access a detail record for this cliente."""
        return reverse('miembro-update', args=[int(self.id)])

    @property
    def edad(self):
        return relativedelta(datetime.now().date(), self.fecha_nacimiento).years

    @property
    def edad_por_anio(self):
        return datetime.now().date().year - self.fecha_nacimiento.year

contabilidad/models.py
from django.urls import reverse
from django.db import models
from club.models import Miembro
from django.db.models import Sum
import uuid


class CuentaContable(models.Model):
    cuenta = models.CharField(max_length=25)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return f'{self.cuenta }'


class Concepto(models.Model):
    concepto = models.CharField(max_length=25)
    descripcion = models.TextField(blank=True)

    def __str__(self):
        return f'{self.concepto}'


class Entrada(models.Model):
    folio = models.CharField(max_length=8, blank=True)
    fecha_pago = models.DateField()
    de = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT,
    )
    notas = models.TextField(blank=True)

    # class Meta:
    #     ordering = ['fecha_pago', 'id']

    def __str__(self):
        return f'{self.id} - {self.de} por: ${self.total_importe}'

    def get_absolute_url(self):
        return reverse('entrada-detail', kwargs={'pk': self.pk})

    @property
    def mes_pago(self):
        return self.fecha_pago.month

    @property
    def anio_pago(self):
        return self.fecha_pago.year

    @property
    def total_importe(self):
        return ConceptoEntrada.objects.filter(entrada=self).aggregate(Sum('importe'))['importe__sum']

    @property
    def conceptos(self):
        return ', '.join(ConceptoEntrada.objects.filter(entrada=self).values_list('concepto__concepto', flat=True))

    @property
    def cuentacontables(self):
        return ', '.join(ConceptoEntrada.objects.filter(entrada=self).values_list('cuenta_contable__cuenta', flat=True))


class ConceptoEntrada(models.Model):
    entrada = models.ForeignKey(
        Entrada,
        on_delete=models.CASCADE,
    )
    miembro = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT
    )
    concepto = models.ForeignKey(
        Concepto,
        on_delete=models.PROTECT,
    )
    cuenta_contable = models.ForeignKey(
        CuentaContable,
        on_delete=models.CASCADE,
    )
    importe = models.FloatField()

    def __str__(self):
        return f'pago para {self.miembro} por {self.concepto} por {self.importe}'


class Salida(models.Model):
    folio = models.CharField(max_length=30, blank=True)
    fecha_pago = models.DateField()
    de = models.ForeignKey(
        Miembro,
        on_delete=models.PROTECT,
    )
    proveedor = models.CharField(
        max_length=100
    )
    notas = models.TextField(blank=True)

    # class Meta:
    #     ordering = ['fecha_pago', 'proveedor']

    def get_absolute_url(self):
        return reverse('salida-detail', kwargs={'pk': self.pk})

    @property
    def mes_pago(self):
        return self.fecha_pago.month

    @property
    def anio_pago(self):
        return self.fecha_pago.year

    @property
    def total_importe(self):
        return ConceptoSalida.objects.filter(salida=self).aggregate(Sum('importe'))['importe__sum']

    @property
    def conceptos(self):
        return ', '.join(ConceptoSalida.objects.filter(salida=self).values_list('concepto', flat=True))

    @property
    def cuentacontables(self):
        return ', '.join(ConceptoSalida.objects.filter(salida=self).values_list('cuenta_contable__cuenta', flat=True))


class ConceptoSalida(models.Model):
    salida = models.ForeignKey(
        Salida,
        on_delete=models.PROTECT,
    )
    concepto = models.CharField(max_length=100)
    cuenta_contable = models.ForeignKey(
        CuentaContable,
        on_delete=models.CASCADE,
    )
    importe = models.FloatField()

    def __str__(self):
        return f'{self.concepto} ${self.importe}'

club/forms.py
from django import forms
from django.shortcuts import render
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column, Div, Fieldset, HTML
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab
from .models import Miembro, Familia


class MiembroAddForm(forms.ModelForm):
    class Meta:
        model = Miembro
        fields = '__all__'

        widgets = {
            'fecha_nacimiento': forms.DateInput(attrs={'id': 'datepicker'}),
            # 'solicitante': forms.DateInput(attrs={'type': 'hidden'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Fieldset('Datos del miembro',
                     Row(
                         Column('nombre', css_class='form-group col-md-4 mb-0'),
                         Column('apellido_paterno',
                                css_class='form-group col-md-4 mb-0'),
                         Column('apellido_materno',
                                css_class='form-group col-md-4 mb-0'),
                     ),
                     Row(
                         Column('sexo', css_class='form-group col-md-4 mb-0'),
                         Column('fecha_nacimiento',
                                css_class='form-group col-md-4 mb-0'),
                         Column('familia',
                                css_class='form-group col-md-4 mb-0'),
                     ),
                     ),
            Fieldset('Datos del club',
                     Row(
                         Column('tipo_miembro',
                                css_class='form-group col-md-6 mb-0'),
                         Column('clase', css_class='form-group col-md-6 mb-0'),
                     ),
                     Field('miembro_iglesia'),

                     ),
        )
        self.helper.add_input(Submit('submit', 'Aceptar'))


class FamiliaAddForm(forms.ModelForm):
    class Meta:
        model = Familia
        fields = ['nombre_familia']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Field('nombre_familia'),
        )
        self.helper.add_input(Submit('submit', 'Aceptar'))

club/views.py
from .utils import Calendar
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic import ListView, DetailView, TemplateView
from django.db.models import Count
from . import models, forms
from contabilidad.models import Entrada, ConceptoEntrada
from django_pandas.io import read_frame
from django.db.models import Avg, Count, Min, Sum
import pandas as pd
import numpy as np


from datetime import datetime, date, timedelta
from django.utils.safestring import mark_safe
import calendar
calendar.setfirstweekday(calendar.SUNDAY)


class ClubDashboard(PermissionRequiredMixin, TemplateView):
    permission_required = 'club.view_miembro'
    template_name = 'club/miembro_dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        familias = models.Familia.objects.all()
        context['familia_list'] = familias
        miembros = models.Miembro.objects.all()
        context['miembro_count'] = models.Miembro.objects.count()

        df_miembros = read_frame(miembros, fieldnames=['id', 'nombre', 'apellido_paterno', 'apellido_materno',
                                                       'fecha_nacimiento', 'sexo', 'familia', 'tipo_miembro', 'clase',
                                                       'clase__hexcolor', 'miembro_iglesia',])

        # por tipo de miembro
        df_tipo_miembro_count = df_miembros.groupby(
            ['tipo_miembro'])['tipo_miembro'].count().reset_index(name='counts').to_dict("index")
        context['tipo_miembro_count'] = df_tipo_miembro_count

        # por clase de miembro
        df_clase_miembro_count = df_miembros.groupby(['clase', 'clase__hexcolor'])[
            'clase'].count().reset_index(name='counts').to_dict("index")
        context['clase_miembro_count'] = df_clase_miembro_count

        # por tipo - clase de miembro
        df_general_miembro_count = df_miembros.groupby(['tipo_miembro', 'clase', 'clase__hexcolor', ])[
            'clase'].count().reset_index(name='counts')
        # print(df_general_miembro_count)

        context['general_miembro_count'] = df_general_miembro_count.to_dict(
            "index")

        # print(df_miembros)

        pivote_table = pd.pivot_table(
            df_miembros,
            index=['tipo_miembro', 'clase',],
            columns=[],
            values=['id'],
            aggfunc=lambda x: len(x.unique()),
            fill_value='',
            margins=True,
            margins_name='Total',
        )

        # print(pivote_table)

        context['miembros_tipos'] = pivote_table.to_html(
            classes=["table", "table-sm", "table-striped",
                     "table-bordered"],
            border=0,
            # table_id='dataTable',
            # float_format='${:,.2f}'.format,
            index=True
        )

        return context


class MiembrosListView(PermissionRequiredMixin, ListView):
    permission_required = 'club.view_miembro'
    model = models.Miembro


class MiembroDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'club.view_miembro'
    model = models.Miembro


class MiembroUpdateView(PermissionRequiredMixin, UpdateView):
    permission_required = 'club.change_miembro'
    model = models.Miembro
    form_class = forms.MiembroAddForm
    template_name = r'generic_form.html'


class MiembroCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'club.add_miembro'
    model = models.Miembro
    form_class = forms.MiembroAddForm
    template_name = r'generic_form.html'


class FamiliaCreateView(PermissionRequiredMixin, CreateView):
    permission_required = 'club.add_familia'
    model = models.Familia
    form_class = forms.FamiliaAddForm
    template_name = r'generic_form.html'

    def get_success_url(self):
        return reverse_lazy('miembros')


class FamiliaDetailView(PermissionRequiredMixin, DetailView):
    permission_required = 'club.view_familia'
    model = models.Familia

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        familia = self.object
        recibo = Entrada.objects.filter(
            de__in=familia.miembro_set.all()
        )
        # recibo = Recibo.objects.filter(
        #     recibos__miembro__in=familia.miembro.all()
        # )
        conceptopago = ConceptoEntrada.objects.filter(
            miembro__in=familia.miembro_set.all()
        )

        context['importe_total'] = conceptopago.aggregate(
            Sum('importe'))
        context['id_count'] = conceptopago.count()
        if conceptopago:
            df = read_frame(conceptopago)
            pivote_table = pd.pivot_table(
                df,
                index=['concepto', ],
                columns=['miembro', ],
                values=['importe'],
                aggfunc=np.sum,
                fill_value='',
                margins=True,
                margins_name='Total',
            )

            context['reporte_conceptos'] = pivote_table.to_html(
                classes=["table", "table-sm", "table-striped",
                         "table-bordered"],
                border=0,
                # table_id='dataTable',
                float_format='${:,.2f}'.format,
                index=True
            )

        context['conceptopago_list'] = conceptopago
        context['recibo_list'] = recibo
        return context


class CalendarioCumples(LoginRequiredMixin, TemplateView):
    template_name = 'club/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context


def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()


def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month


def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

club/templates/club/familia_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Familia: {{familia.nombre_familia}}</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group  me-2" role="group" aria-label="Basic example">
        </div>
    </div>
</div>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item" aria-current="page"><a href="{% url 'miembros' %}">Miembros</a></li>
        <li class="breadcrumb-item active" aria-current="page">Familia: #{{familia.id}}</li>
    </ol>
</nav>

<div class="row my-4">
    <div class="col-12 col-md-6 col-lg-3 mb-4 mb-lg-0">
        <ul class="list-group ">
            <li class="list-group-item active" aria-current="true">Miembros de la familia</li>
            {% for miembro in familia.miembro_set.all %}
            <li class="list-group-item">
                <a href="{{miembro.get_absolute_url}}" class="">
                    {{miembro.nombre}} {{miembro.apellido_paterno}}
                    {{miembro.apellido_materno}}
                </a> - <small class="text-muted">{{miembro.get_tipo_miembro_display}}</small>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col">
        <div class="card shadow-sm">
            <h5 class="card-header bg-primary text-white">Reporte de pagos por conceptos</h5>
            <div class="card-body">
                <p class="card-text">
                    Este muestra la informacion de la distribucion por conceptos de cada uno de los pagos, no muestra
                    cuando se pagaron.
                </p>
                {{reporte_conceptos|safe}}
            </div>
        </div>
    </div>
</div>
<div class="row my-4">
    <div class="col">
        <div class="card shadow-sm">
            <h5 class="card-header bg-primary text-white">Pagos realizados - Lista de raya</h5>
            <div class="card-body">
                {% if recibo_list %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm small" id="dataTable">
                        <caption>Pagos realizados</caption>
                        <thead>
                            <tr>
                                <th scope="col" class="text-center">Recibo</th>
                                <th scope="col">Fecha de pago</th>
                                <th scope="col">de</th>
                                <th scope="col">Conceptos</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for recibo in recibo_list %}
                            <tr>
                                <th scope="row" class="font-monospace text-center">
                                    {{recibo.id}}
                                </th>
                                <td>{{recibo.fecha_pago}}</td>
                                <td>{{recibo.de}}</td>
                                <td>
                                    <table class="table table-borderless table-sm small">
                                        <tbody>
                                            {% for concepto in recibo.conceptoentrada_set.all %}
                                            <tr>
                                                <td>{{concepto.miembro}}</td>
                                                <td>{{concepto.concepto}}</td>
                                                <td class="text-end">{{concepto.importe}}</td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <td> </td>
                                            <td> </td>
                                            <td class="text-end border-top">
                                                ${{recibo.total_importe|floatformat:2|intcomma}}</td>
                                        </tfoot>
                                    </table>
                                </td>
                                <td class="text-center">
                                    <a href="{{recibo.get_absolute_url}}" class="">Ver recibo</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td></td>
                                <td></td>
                                <td class="text-center">
                                    {{id_count|intcomma}}
                                </td>
                                <td class="text-end">
                                    ${{importe_total.importe__sum|floatformat:2|intcomma}}
                                </td>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- <div class="row my-4">
    <div class="col">
        <div class="card shadow-sm">
            <h5 class="card-header bg-primary text-white">Pagos realizados</h5>
            <div class="card-body">
                {% if conceptopago_list %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm small" id="dataTable">
                        <caption>Pagos realizados</caption>
                        <thead>
                            <tr>
                                <th scope="col" class="text-center">Recibo</th>
                                <th scope="col">Fecha de pago</th>
                                <th scope="col">Miembro</th>
                                <th scope="col">Concepto</th>
                                <th scope="col" class="text-end">Importe</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for concepto in conceptopago_list %}
                            <tr>
                                <th scope="row" class="font-monospace text-center">
                                    {{concepto.Recibo.id}}
                                </th>
                                <td>{{concepto.Recibo.fecha_pago}}</td>
                                <td>{{concepto.miembro}}</td>
                                <td>{{concepto.concepto}}</td>
                                <td class="text-end">${{concepto.importe|floatformat:2|intcomma}}</td>
                                <td class="text-center">
                                    <a href="{{concepto.Recibo.get_absolute_url}}" class="">Ver recibo</a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td class="text-center">
                                    {{id_count|intcomma}}
                                </td>
                                <td class="text-end">
                                    ${{importe_total.importe__sum|floatformat:2|intcomma}}
                                </td>
                                <td></td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div> -->

{% endblock %}

{% block JavaScript %}

{% endblock %}

club/templates/club/miembro_detail.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load static %}

{% block header %}
{% endblock %}

{% block content %}
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Perfil del miembro</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group me-2">
            {% if perms.club.add_miembro %}
            <a class="btn btn-sm btn-outline-primary" href="{{miembro.get_absolute_url_update}}">Editar</a>
            {% endif %}
        </div>
    </div>
</div>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'miembros' %}">Miembros</a></li>
        <li class="breadcrumb-item active" aria-current="page">
            Miembro - #{{miembro.id}}
        </li>
    </ol>
</nav>
<div class="row">
    <div class="col-md-3 border-right">
        <div class="d-flex flex-column align-items-center text-center p-3 py-5">
            {% if miembro.sexo == "M"%}
            <img src="{% static 'svg/undraw_male_avatar_g98d.svg' %}" width="150px" alt="" />
            {% elif miembro.sexo == "F"%}
            <img src="{% static 'svg/undraw_female_avatar_efig.svg' %}" width="150px" alt="" />
            {% endif %}

            <span class="font-weight-bold">
                {{miembro.nombre}} {{miembro.apellido_paterno}} {{miembro.apellido_materno}}
            </span>
            <span class="text-black-50">{{miembro.tipo_miembro}}</span>
            <span>
            </span>
        </div>
    </div>
    <div class="col-md-9">
        <div class="p-3 py-5">
            <div class="row mt-2">
                <div class="row">
                    <div class="col-md-6 ">
                        <label>Clase a la que pertenece</label>
                    </div>
                    <div class="col-md-6 fw-bold">
                        <p>{{miembro.clase}}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Familia</label>
                    </div>
                    <div class="col-md-6 fw-bold">
                        <p>
                            <a href="{{miembro.familia.get_absolute_url}}" class="">
                                {{miembro.familia}}
                            </a>
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Fecha nacimiento</label>
                    </div>
                    <div class="col-md-6">
                        <p>{{miembro.fecha_nacimiento}}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Edad</label>
                    </div>
                    <div class="col-md-6">
                        <p>{{miembro.edad}} año(s)</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>Sexo</label>
                    </div>
                    <div class="col-md-6">
                        <p>{{miembro.get_sexo_display}}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <label>¿Es miembro de la Iglesia Adventista?</label>
                    </div>
                    <div class="col-md-6">
                        <p>{{miembro.miembro_iglesia}}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% if perms.contabilidad.view_recibo%}
<div class="row my-4">
    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Pagos realizados</h5>
                {% if conceptopago_list %}
                <div class="table-responsive">
                    <table class="table table-striped table-sm small" id="dataTable">
                        <thead>
                            <tr>
                                <th scope="col">Recibo</th>
                                <th scope="col">Fecha de pago</th>
                                <th scope="col">Concepto</th>
                                <th scope="col">Importe</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for concepto in conceptopago_list %}
                            <tr>
                                <th scope="row" class="font-monospace">
                                    <a href="{{concepto.Recibo.get_absolute_url}}" class="">{{concepto.Recibo.id}}</a>
                                </th>
                                <td>{{concepto.Recibo.fecha_pago}}</td>
                                <td>{{concepto.concepto}}</td>
                                <td>${{concepto.importe|floatformat:2|intcomma}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% endif %}
                <a class="btn btn-primary" href="{% url 'entrada-new' %}" role="button">
                    Realizar un nuevo pago
                </a>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

{% block JavaScript %}

{% endblock %}